//pipeline steps configuration
steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-us01
    integrationFlowId: S0010832946-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-us01
    integrationFlowId: S0010832946-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-us01
    integrationFlowId: S0010832946-flow4
    integrationFlowName: S0010832946-flow4
    packageId: CICD
    filePath: S0010832946-flow4.zip